### ISSUE TITLE
GoogleApiClient SignIn

### ISSUE THREAD

**Issue by mbluewolf** [JcDenton86/cordova-plugin-jc-googledrive#4]
Hello,  thank you for the code.
I installed the plugin in vs2015 cordova project, created test code and it runs to the point where it starts the signin process presenting the phone accounts to choose from, but it stops after choosing the account.
The app is signed with a private keystore file, so it installs ok.
I created credentials at the google api console site, client_id.json which tested in .NET client and worked fine.
Back to android, i dont understand how to integrate this credentials so that the plugin can complete the signin.   Can anyone help me with this?

**Comment by JcDenton86** [comment]
Hi, you create an oauth client id on developer console and you have to add the app package and the SHA1 of you keystore as described at step 2 in readme.

There is no need to integrate your credentials inside the app on Android.

**Comment by rafaellop** [comment]
@mbluewolf This is probably the same issue I had. You must build a release version. It won't work with a debug version started with e.g. `cordova run android`

**Comment by JcDenton86** [comment]
See the attached screenshot of my setup on developer console. I have 3 oath ids for debug because I develop on different machines and the debug.keystore SHA1 is different on each pc. And also I have one release oath id for my app. 

I cannot understand what is going wrong, but the plugin works with the debug SHA1 without errors. Make sure that you add the correct SHA1 and app package on each oath id you create.

![scr](https://cloud.githubusercontent.com/assets/1433320/24676268/09413fb6-198b-11e7-9c8f-6c6793c254ab.png)

**Comment by rafaellop** [comment]
Maybe you could add a tutorial how to get the SHA1 for debug APKs because if I try to jarsign the `cordova build` output with a debug keystore the jarsigner reports errors like `invalid entry compressed size`. It seems that the debug package is already signed by graddle but I cannot find which keystore it uses and how to list the SHA1 for the cordova debug APK. And of course I cannot sign it with my own.

**Comment by JcDenton86** [comment]
The debug.keystore is created automatically. The path depending your OS is different. for instance on a mac you can find the SHA1 of the debug keystore usign this command:

`keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android `

This is out of the purpose of this plugin and signing debug or release is a standard on Android development (check the [docs](https://developer.android.com/studio/publish/app-signing.html) about Expiry of the debug certificate.

**Comment by rafaellop** [comment]
I know this but I cannot find the debug keystore used by graddle on my Windows 10. For sure it is not in the path suggested in SO.

**Comment by JcDenton86** [comment]
Maybe you need to install an IDE (i.e. Android Studio). Try this too.

**Comment by JcDenton86** [comment]
Closing this issue because it does not have to do with the plugin but with local setup of the SDK.
